name: Build

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
        cache-dependency-path: package-lock.json
    - name: version
      run: echo "::set-output name=version::$(cat VERSION.md)"
      id: version
    - run: npm ci
    - name: Publish release
      run: npm run build --if-present
    # no tests for now...
#    - run: npm test

    # publish
    - name: Publish
      run: cd ./.output/ && tar -czf veil.tools-${{ steps.version.outputs.version }}.tar.gz *
    - uses: actions/upload-artifact@v2
      with:
        name: veil.tools-${{ steps.version.outputs.version }}
        path: ./.output/veil.tools-${{ steps.version.outputs.version }}.tar.gz